---
- hosts: production
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: apt -y update && apt install -y python-minimal
      sudo: yes
    - setup:
  vars:
    app_name: thess_geonode
    github_user: okgreece 
    server_name: riskdata.thessaloniki.gr
    repo_name: thess_geonode
    deploy_user: root
  roles:
     - { role: GeoNode.geonode }
